### ISSUE TITLE
some nc versions don't support -c

### ISSUE THREAD

**Issue by ahillio** [EddySchauHai/bashttp#3]
On Ubuntu 20.04.3 LTS the default version of `nc` doesn't have a `-c` option, so `server.sh` just prints miles of

```
nc: invalid option -- 'c'
usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-M ttl]
          [-m minttl] [-O length] [-P proxy_username] [-p source_port]
          [-q seconds] [-s source] [-T keyword] [-V rtable] [-W recvlimit] [-w timeout]
          [-X proxy_protocol] [-x proxy_address[:port]]           [destination] [port]
```

Is `-c` necessary for this to work as you intend?  

`man nc` has an explanation of how *"you still can execute a command after connection being established by redirecting file descriptors."* but I don't know what command I'd want to run in that case nor how this little bashloop would need to be modified.

Cool project! I just saw you post it on reddit and gave it a try :)

**Comment by EddySchauHai** [comment]
Thanks! Although I didn't personally post it on Reddit, I don't really know why a random small script blew up quite so much ha! 

So `-c` is used to terminate the `nc` connection after `EOF`. This is because `nc` is unable to hold multiple connections simultaneously so it gives it pseudo-concurrency (as it's only hosting a static file). I'll take a look at `-c` failing on Linux, I'm running MacOS :)
